name: Run API Tests Sequentially

# Trigger this workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment (you can specify the Node.js version you need)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies (replace with your package manager if different)
      - name: Install dependencies
        run: npm ci

      # Step 4: Run API tests sequentially and generate reports
      - name: Run API Tests Sequentially
        env:
          CYPRESS_MULTI_REPORTER_OPTIONS: >-
            reporterEnabled=spec,mocha-junit-reporter,mochawesome;
            mochawesomeReporterOptions.reportDir=cypress/results/mochawesome;
            mochawesomeReporterOptions.overwrite=false;
            mochawesomeReporterOptions.html=false;
            mochawesomeReporterOptions.json=true;
            mochaJunitReporterReporterOptions.mochaFile=cypress/results/junit/results-[hash].xml
        run: |
          npx cypress run --reporter cypress-multi-reporters --reporter-options "$CYPRESS_MULTI_REPORTER_OPTIONS" --spec cypress/e2e/1-getting-started/01_LoginandCreateNewPost.spec.js
          npx cypress run --reporter cypress-multi-reporters --reporter-options "$CYPRESS_MULTI_REPORTER_OPTIONS" --spec cypress/e2e/1-getting-started/02_GlobalFeedLikesCount.spec.js
          npx cypress run --reporter cypress-multi-reporters --reporter-options "$CYPRESS_MULTI_REPORTER_OPTIONS" --spec cypress/e2e/1-getting-started/03_DeletePostArticle.spec.js

      # Step 5: Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Cypress-Test-Reports
          path: cypress/results/mochawesome/*.json
