name: Run API Tests Sequentially

# Trigger this workflow on every push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment (you can specify the Node.js version you need)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies (replace with your package manager if different)
      - name: Install Dependencies
        run: npm install

      # Step 4: Run API tests one by one
      - name: Run API Tests
        run: |
          # Run your API tests sequentially using a testing framework like Mocha, Cypress, or Newman
          
          # Example for Cypress (sequential run of API tests):
          npx cypress run --spec cypress/e2e/api_tests/test1.spec.js
          npx cypress run --spec cypress/e2e/api_tests/test2.spec.js
          npx cypress run --spec cypress/e2e/api_tests/test3.spec.js
          
      

      # Optional Step: Publish test results (you can publish results or use a CI test reporter)
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cypress/reports/

